#!/sbin/runscript
extra_commands='reset'

pidfile='/var/run/dellfand.pid'

start() {
	ebegin "Starting dellfand"
	start-stop-daemon --background --pidfile "${pidfile}" --make-pidfile \
		/usr/sbin/dellfand 0 ${sleep_time} ${fan_off_temp} ${fan_on_lowspeed_temp} ${fan_on_high_speed_temp}
	eend $?
}

reset() {
	ebegin "Reseting fan state"
	stop
	/usr/sbin/dellfand 0 1 25 25 25 >/dev/null 2>&1 &
	reset_pid="$!"
	sleep 3
	kill "$reset_pid"
	eend $?
	start
}

