# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="HINRIK"


inherit perl-module

DESCRIPTION="A POE component for building IRC clients"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/IRC-Utils-0.10
	dev-perl/POE
	perl-gcpan/POE-Component-Syndicator
	>=perl-gcpan/POE-Filter-IRCD-2.42
	dev-lang/perl"
