#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
        need localmount
	after logger
}

start() {
        ebegin "Starting auto nice daemon"
        start-stop-daemon --start --quiet --exec /usr/sbin/and -- $AND_FLAGS
        eend $?
}

stop() {
        ebegin "Stopping auto nice daemon"
        start-stop-daemon --stop --quiet --exec /usr/sbin/and
        eend $?
}
